### ISSUE TITLE
Public Sharing

### ISSUE THREAD

**Issue by subh-775** [KARTIK-PANDEY/Ai_Based_Chatbot-TENET_BOT#1]
Bro don't share your API key Publicly. Instead add "write_your_api_key_here" in msg app.py

**Comment by KARTIK-PANDEY** [comment]
Surely brother, Thank you soo much for Finding this Incorrection.
I haven't check this Blender while uploading, hence This Mistake take
place...
Whereas, I Have peoples like you who help me in all possible way...
Thanks brother 🫂❤

**Comment by KARTIK-PANDEY** [comment]
Changes have been made.
